added-footer
TikhonenkoVV/fson-69_bl_01_02 pull request #17
Opened 2022-11-20 15:38 UTC by Nasvishchuk-Olena

2022-11-21 23:56 UTC, TikhonenkoVV requested changes

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/partials/footer-right.html
> +    <svg class="logo__icon" width="86px" height="37px">
Розмір іконки 86х39 без одиниць виміру

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/sass/components/__footer.scss
> +}
Прибрати взагалі стилі .eero-footer-list, скидання стилів є у _base.css

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/partials/footer-right.html
> +    <use href="./images/symbol-defs-optima.svg#icon-Frame-1"></use>
Не вірний шлях до іконки. Повинен бути ./images/icons.svg#mainlogo

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/partials/footer-right.html
> +                </svg>
Що це за іконка? Іконки нема на макеті. Видалити.

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/partials/footer-right.html
> +</footer>
Виправити назви класів за технологією БЕМ.
Виправити шляхи до іконок соціальних мереж (спрайт у проекті знаходиться у images\icon.svg).
Виправити розміри іконок відповідно до макета.

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/partials/footer-right.html
> +                <span class="visually-hidden">Email</span>
Сенс цього спану? Видалити.

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/sass/components/__footer.scss
> +}
Прибрати .visually-hidden, в ньому нема сенсу, бо використовується тільки в спані, який теж не має сенсу.

2022-11-21 23:56 UTC, TykhonenkoVV commented on src/sass/components/__footer.scss
> +    gap: 92px;
Прибрати gap. Замість цього спискам задати фіксовану ширину 250px (як на макеті)

2022-11-21 23:56 UTC, TikhonenkoVV commented on src/sass/components/__footer.scss
> +    border-bottom: 1px solid #FFFFFF;
Верхній, лівий та правий бордер - none, прозорий колір бордера прибрати.

2022-11-21 23:56 UTC, TikhonenkoVV commented on src/sass/components/__footer.scss
> +    outline: none;
Не можна прибирати outline!!!

2022-11-21 23:56 UTC, TikhonenkoVV commented on src/sass/components/__footer.scss
> +}
Виправити розміри та відступи елементів, а також всі шрифти відповідно до макету.
Кольори приписати використовуючи змінні які знаходяться у файлі _variables.scss
Виправити назву файлу _footer.scss
Додати стилі для іконок

2022-11-22 00:04 UTC, TikhonenkoVV requested changes

2022-11-22 00:04 UTC, TikhonenkoVV commented on src/partials/footer-right.html
> +<footer>
Тег <footer> не потрібен, він є у index.html

2022-11-22 00:18 UTC, TikhonenkoVV commented on src/sass/components/__footer.scss
> +}
Також у index.scss імпортуй _footer.scss

2022-11-30 09:36 UTC, TikhonenkoVV approved these changes

2022-11-30 09:48 UTC, merged