About section
TikhonenkoVV/fson-69_bl_01_02 pull request #23
Opened 2022-11-28 14:08 UTC by Oleg833

2022-11-29 10:04 UTC, kozhushna requested changes

2022-11-29 10:04 UTC, kozhushna commented on src/partials/about.html
> +          <div class="about__icon-box">
Привіт! Олег, цей дів з цим класом зайвий, він ніде не використовується

2022-11-29 10:04 UTC, kozhushna commented on src/sass/components/_about.scss
> +.about__control-box {
Цього класу також можна позбутися, в тебе вже є .about__list та .about__item, які можна доповнити, наприклад так (те, що закоментовано, то було і тепер можна прибрати): 
.about__list {
  display: flex;
  //   justify-content: space-between;
  gap: 151px;
  justify-content: center;
  //   height: 100%;
}
.about__item {
  width: 199px;
  display: flex;
  flex-direction: column;
  min-height: 427px;
}
Зроби, будь-ласка, не фіксовану висоту, а min-height, щоб у разі, якщо додається ще текст, нічого не їхало, а розширювалось по вертікалі.

2022-11-29 10:04 UTC, kozhushna commented on src/sass/components/_about.scss
> +.about__icon {
Щось у нас не так зі спрайтом, напевне, але замість картинки відображується просто синій квадратик. 
Скрін:
![image](https://user-images.githubusercontent.com/113435931/204494406-8f011c73-46a8-4d84-b114-43272c6526b6.png)

Також можеш використати змінну fill: $colorAccent;
Також краще вставляти розміри картинки у тег svg (svg width="77" height="77"), а не прописувати в CSS, бо якщо б ці картинки були різного розміру (як, наприклад, телефончик та конвертик у наших ДЗ), то прийшлося б "навішувати" на кожну картинку свій клас

2022-11-29 10:04 UTC, kozhushna commented on src/sass/components/_about.scss
> +.about__link {
Лінка зайняла всю ширину батька, тому таке підкреслення робити не можна. 
![image](https://user-images.githubusercontent.com/113435931/204496271-db5845a8-ee91-4fba-b7c4-304c7b51f051.png)

Тут потрібно робити чи через псевдоелементи (як в домашці) чи просто текст лінки обгорнути в спан з класом і тоді йому вже давати нижню границю та не забути про відстань від тексту в 5рх.
Також додай, будь ласка ховер і фокус на лінку . Не знаю, як ти вирішиш зробити лінку, додам скрін, як, наприклад, можна через спан (звісно, це моє рішення і не факт, що вірно, але працює):
 
![image](https://user-images.githubusercontent.com/113435931/204498059-e2dbae20-a20e-4a24-9b44-21548f13e238.png)
А так я робила лінку в своїй секції:
![image](https://user-images.githubusercontent.com/113435931/204498366-6bb20e09-58e5-4b49-9e14-ea190141b527.png)

2022-11-29 10:55 UTC, Oleg833 commented on src/sass/components/_about.scss
> +.about__icon {
Розміри прописав в свг - виправив іконки приїхали

2022-11-29 11:22 UTC, Oleg833 commented on src/partials/about.html
> +          <div class="about__icon-box">
Виправлено! Цей дів я бачив і повинен був прибрати, дякую за уважність!

2022-11-29 11:46 UTC, Oleg833 commented on src/sass/components/_about.scss
> +.about__control-box {
Виправлено! Точно, ми ж можемо gap і на лішки min-height, тоді і дів лишній, дякую.

2022-11-29 12:45 UTC, Oleg833 commented on src/sass/components/_about.scss
> +.about__link {
Виправлено! Ховер і фокус думав і протупив, а Маржин райт авто вирішує проблему зі спаном і шириною. Тут для спану, на мій погляд забагато почестей так як і для псевдоелемента.
.about__link {    
    font-size: 14px;
    line-height: 1.15;
    color: $colorTextPrimary;
    border-bottom: solid 1px currentColor;
    text-transform: uppercase;
    padding-bottom: 5px;
    margin-right: auto;    

    &:hover,
    &:focus {
        color: $colorAccent;
        border-bottom: solid 1px $colorAccent;
    }
}

2022-11-29 15:45 UTC, TikhonenkoVV approved these changes

2022-11-30 09:20 UTC, TikhonenkoVV approved these changes

2022-11-30 09:21 UTC, merged